### ISSUE TITLE
NavBar issue on hover in Darkmode + sugestie

### ISSUE THREAD

**Issue by georged17** [ViorelMocanu/DDD#1]
În dark mode, la hover pe link-urile din navbar, text-ul linkului preia culoarea aceea de galben și deci nu mai poate fi citit.

EDIT: observ aceeasi problema si pe mobile + meniul ramane deschis după ce dai click pe unul din linkuri.

Also, ca sugestie pentru site in general, aș adăuga un buton de "Back to top of the page", poate ar fi util.

**Comment by ViorelMocanu** [comment]
Merci pentru finding, mă uit zilele astea și revin cu un pull request care să rezolve problemele. :)
